### ISSUE TITLE
There are some problems that need to confirm

### ISSUE THREAD

**Issue by nolsherry** [luisvinicius167/mockstate#24]
Hello @luisvinicius167,
I am one of the member in [cdnjs](https://github.com/cdnjs/cdnjs). 
There are some problems that need to confirm. 
The library riotux [riotux](https://cdnjs.com/libraries/riotux) in cdnjs seems to be the same as [mockstate](https://github.com/luisvinicius167/mockstate).
Therefore, would you want to add mockstate in cdnjs, or just integrate into riotux in cdnjs?
Thanks!

cdnjs/cdnjs#7770 
cdnjs/cdnjs#9323
cdnjs/cdnjs#9964

**Comment by luisvinicius167** [comment]
Hi!! You can just add mockstate, will be awesome if you can!

**Comment by nolsherry** [comment]
@luisvinicius167 thanks for your response, we will just add mockstate.
