### ISSUE TITLE
Actions being triggered multiple times

### ISSUE THREAD

**Issue by marciodsousa** [luisvinicius167/mockstate#25]
I am building an application using mockstate, and I noticed that quite often I get the same action to be triggered multiple times, although I am pretty sure i only dispatch it once.

Are there any other reports on this? Or does it make any sense even?

I am basically just using _dispatch_ and _subscribe_. And for one dispatched action I get multiple entries in the subscribe (for the same data.action).

**Comment by luisvinicius167** [comment]
Hi @marciodsousa! So, basically the subscribe method works pushing your components into an Array. If your subscribe two components, the subscribe method will be triggered two times. If you can check out https://github.com/luisvinicius167/dutier. It's production ready and are very simple too. And it's async by default. :)

**Comment by marciodsousa** [comment]
@luisvinicius167 thank you for your prompt response (and sorry for my late reply)

As it turns out, I was subscribing my main component twice and not managing subscriptions properly.

About your suggestion, I'll definitely check it!

Not an issue. Closed.
